### ISSUE TITLE
set charset utf8 does not work or is acting weird

### ISSUE THREAD

**Issue by weha** [joshcam/PHP-MySQLi-Database-Class#197]
my mysql class implementation gives normal characters, for example: Biétrix
this mysqli class gives out this on the same page: BiÃ©trix

I noticed you set the UTF8 charset in the class but something is wrong
utf8_decode fixes the string, but firefox page info says Encoding UTF-8.
When I comment out the $this->_mysqli->set_charset ('utf8'); it works just fine

html contains: 
- <!DOCTYPE HTML>
- meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
- tried this as well: meta charset="UTF-8">

mysql column: utf8_swedish_ci

**Comment by avbdr** [comment]
we should refactor this part of the code somehow to get rid of hardcoded utf8 charset.

**Comment by avbdr** [comment]
thats fixed with a proper fix in https://github.com/avbdr/PHP-MySQLi-Database-Class. Should be merged here soon.

**Comment by weha** [comment]
Thank you for your quick replies and fixes.

While it is a nice addition to have the charset as a variable it does not really fix the issue.
This might however not be a bug in this class but a misunderstanding in how the charset works?
If I use your fork I again get garbled names unless I set your $charset variable to NULL, am I doing it wrong?

**Comment by avbdr** [comment]
try to dump your database and check which charset your tables are using. I think they are not UTF8.
The purpose of the patch is to allow setting character to NULL in situations like that.

**Comment by weha** [comment]
It is actually utf8 but utf8_swedish_ci, when I set it to this value instead of just utf8 it works like it's supposed to.
Maybe it is best to default this to null instead of actual value so you can override it as setting it would be the exception instead of the other way around.

Just my 2 cents, thank you for your assistance.

**Comment by avbdr** [comment]
I agree with you here, but the goal were to maintain backwards compatibility with old behavoir.
At least now there is an api to change encoding for a cases which were 'broken' before.
